version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # Install package
            sudo pip install -U pipenv
            pipenv install .
      - run:
          command: |  # Run tests
            pipenv install pytest
            pipenv run pytest python/fastgrouper/test/ -s -vv

workflows:
  build_test:
    jobs:
      - build_test
