version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # Install package
            sudo pip install pipenv
            pipenv install .
      - run:
          command: |  # Run tests
            pipenv shell
            pytest -s -vv python/fastgrouper/test/

workflows:
  build_test:
    jobs:
      - build_test
