version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # Install package
            python3 -m venv build_test
            source build_test/bin/activate
            python3 setup.py install
      - run:
          command: |  # Run tests
            pipenv run pytest -s -vv

workflows:
  build_test:
    jobs:
      - build_test
